### ISSUE TITLE
[SOLVED] How to install nss-dns4only on centos7 or centos 8

### ISSUE THREAD

**Issue by asdfjklqweruop** [ossobv/nss-dns4only#1]
how to install nss-dns4only on centos7 or centos 8?
step by step tutorial，thank you.

**Comment by wdoekes** [comment]
I assume you can take the compiled .so file from here:

https://github.com/ossobv/nss-dns4only/releases/download/v0.1/libnss_dns4only-0.1.so

And place it NEAR (not over) libnss_dns-2.17.so. I assume that might be in `/lib64`, but it may be elsewhere on your CentOS. If you find `libnss_dns*.so`, and it's a 64-bit binary, you're in the right place:

```console
# file /lib64/libnss_dns-2.17.so 
/lib64/libnss_dns-2.17.so: ELF 64-bit LSB shared object, x86-64 [...]

# cd /tmp/
# wget https://github.com/ossobv/nss-dns4only/releases/download/v0.1/libnss_dns4only-0.1.so

# cp -a libnss_dns4only-0.1.so /lib64/
# ln -s libnss_dns4only-0.1.so /lib64/libnss_dns4only.so.2
# ln -s libnss_dns4only.so.2 /lib64/libnss_dns4only.so

# ldconfig
```

And when you've done that, follow the instructions on changing `/etc/nsswitch.conf`:

https://github.com/ossobv/nss-dns4only#how-to-install
